
# Configuration file for adverse event classification

epochs: 200
eval_every: 10
batch_size: 32
val_size: 0.2

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.000001

scheduler:
  name: cosine
  warmup_epochs: 5