
# Configuration file for masked language modelling

epochs: 20
eval_every: 5
batch_size: 2
val_size: 0.2

encoder:
  num_layers: 6
  num_heads: 8
  model_dim: 256
  embed_dim: 256
  ff_dim: 512

optim:
  name: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  name: cosine
  warmup_epochs: 5