
# Configuration file for masked language modelling

epochs: 1000
eval_every: 10
batch_size: 32
val_size: 0.2

encoder:
  num_layers: 6
  num_heads: 12
  model_dim: 516
  embed_dim: 516
  ff_dim: 516

optim:
  name: adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  name: cosine
  warmup_epochs: 5